name: PHP CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: nanasess/setup-php@v4
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: Run PHPStan
        run: php bin/phpstan analyse

      - name: Run PHPCS
        run: php bin/phpcs

      - name: Run PHPUnit
        run: php bin/phpunit
